import {
  spfOne,
  spfTwo,
  spfThree,
  spfFour,
  bestSellerOne,
  bestSellerTwo,
  bestSellerThree,
  bestSellerFour,
  newArrOne,
  newArrTwo,
  newArrThree,
  newArrFour,
  one,
  two,
  three ,
  four,
  five,
  six,
  seven,
  eight,
  nine,
  ten,
} from "../assets/images/index";

export const navBarList = [
  {
    _id: 1001,
    title: "Басты бет",
    link: "/",
  },
  {
    _id: 1002,
    title: "Смартфондар",
    link: "/shop",
  },
  {
    _id: 1004,
    title: "Байланыс",
    link: "contact",
  },
];

export const SplOfferData = [
  {
    _id: "201",
    img: spfOne,
    productName: "iPhone 13",
    price: 980,
    color: "Жасыл",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "202",
    img: newArrFour,
    productName: "iPhone 15 Pro Max Titanium",
    price: 1790,
    color: "Күлгін",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "RedMi 10 Pro",
    price: 350,
    color: "Күлгін ақ",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Note 10 Plus",
    price: 520,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];

export const paginationItems = [
  {
    _id: 1001,
    img: spfOne,
    productName: "iPhone 13",
    price: 980,
    color: "Жасыл",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1002,
    img: newArrFour,
    productName: "iPhone 15 Pro Max Titnium",
    price: 1790,
    color: "Күлгін",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1003,
    img: spfThree,
    productName: "RedMi 10 Pro",
    price: 350,
    color: "Күлгін ақ",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1004,
    img: spfFour,
    productName: "Note 10 Plus",
    price: 520,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1005,
    img: one,
    productName: "iPhone 14",
    price: 990,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1006,
    img: two,
    productName: "Redmi 10",
    price: 320,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1007,
    img: three,
    productName: "iPhone 15",
    price: 1430,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1008,
    img: four,
    productName: "Redmi 12",
    price: 520,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1009,
    img: five,
    productName: "iPhone 15 Pro",
    price: 1540,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1011,
    img: six,
    productName: "iPhone 13",
    price: 890,
    color: "Ақ",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1012,
    img: seven,
    productName: "Redmi Note 11",
    price: 420,
    color: "Ақ",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1013,
    img: eight,
    productName: "Z Flip 4",
    price: 1210,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1014,
    img: nine,
    productName: "Note 20",
    price: 520,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "203",
    img: spfThree,
    productName: "RedMi 10 Pro",
    price: 350,
    color: "Күлгін ақ",
    badge: false,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: "204",
    img: spfFour,
    productName: "Note 10 Plus",
    price: 520,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1015,
    img: ten,
    productName: "Z Fold",
    price: 520,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1006,
    img: two,
    productName: "Redmi 10",
    price: 320,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
  {
    _id: 1007,
    img: three,
    productName: "iPhone 15",
    price: 1430,
    color: "Ақ",
    badge: true,
    des: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic excepturi quibusdam odio deleniti reprehenderit facilis.",
  },
];
